apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: richard-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: Pod
metadata:
  name: richard-pod
spec:
  containers:
    - name: richard-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: richard-volume
  volumes:
    - name: richard-volume
      persistentVolumeClaim:
        claimName: richard-pvc
